### ISSUE TITLE
Plugin doesn't seem to work on new Sketch with Mojave.

### ISSUE THREAD

**Issue by jplarose80** [juliussohn/sketch-textbox-fit-content#6] opened 2018-10-05 13:42 UTC
Using Sketch 52.1, macOS 10.14.

Plugin does not automatically fit to text anymore, whether the box is too small or too big.

Let me know if you need more info.

**Comment by matt7621** [comment] 2018-10-10 16:28
Im also using Mojave 10.14 but when I updated to latest Sketch 52.1 this plugin does not work anymore.

**Comment by vbodunov** [comment] 2018-10-10 17:08
I'm not on Mojave yet, I'm on OS 10.13.6, but just updated to sketch 52.1. Plugin does not work

**Comment by scood85** [comment] 2018-10-18 14:49
also installed Mojave and plugin doesn´t work anymore :(

**Comment by vbodunov** [comment] 2018-10-18 16:25
Also an issues with the auto-fit feature when text frames are stacked using the auto-layout feature in anima toolkit. You have to click into the text frame (as to edit the content), then exit out of it to resize on it's own.

**Comment by georgeleonardo** [comment] 2018-10-23 09:50
Not working for me too. I'm dying here :(

**Comment by jplarose80** [comment] 2018-10-23 12:39
For people having the same issue as I am, I discovered http://ashung.github.io/Automate-Sketch/ which also resizes the text box, but unfortunately doesn't seem to trim the empty spaces at the start/end. Its a close substitute.

**Comment by juliussohn** [comment] 2018-10-23 18:52
Seems to be caused by an undocumented API change or a bug. I'm on it.

**Comment by splimola** [comment] 2018-10-26 17:12
> Seems to be caused by an undocumented API change or a bug. I'm on it.

Thank you!  Dying for this to work again! Forgot just how tedious Sketch is without this plugin - it really should be a core feature! Keep it up!

**Comment by juliussohn** [comment] 2018-10-28 21:43
I reported the bug in the SketchAPI repo and they committed a fix. I will publish the fixed plugin as soon as the API bug fix will be released in the next Sketch update.

**Comment by splimola** [comment] 2018-11-05 16:36
> I reported the bug in the SketchAPI repo and they committed a fix. I will publish the fixed plugin as soon as the API bug fix will be released in the next Sketch update.

Is this addressed with the recent 52.3 Sketch update?

**Comment by spjpgrd** [comment] 2018-11-26 21:17
> > I reported the bug in the SketchAPI repo and they committed a fix. I will publish the fixed plugin as soon as the API bug fix will be released in the next Sketch update.
> 
> Is this addressed with the recent 52.3 Sketch update?

Doesn't look like it 😢

**Comment by Kaske** [comment] 2019-01-18 13:56
Still not working.

**Comment by SevenZark** [comment] 2019-01-18 16:01
I'm a new user, just installed the plugin. It literally does nothing, each plugin action I attempt failing silently. I'm on Mojave too.

**Comment by splimola** [comment] 2019-01-18 17:02
Should it really take this long to find a fix, forgive me but I don't know, unless the dev just doesn't care?  There have been at least 3 Sketch updates since this was reported and still nothing... Wish there were alternatives out there!

**Comment by juliussohn** [comment] 2019-01-18 17:30
It has been fixed already and will be released in 53. It works in the beta - so I am very optimistic this time
https://github.com/BohemianCoding/SketchAPI/pull/272

**Comment by juliussohn** [comment] 2019-02-06 22:19
Fixed in Sketch 53

**Closed as completed by juliussohn** 2019-02-06 22:19 UTC
